### ISSUE TITLE
清华元宇宙报告3.0，作者可以下载更新下

### ISSUE THREAD

**Issue by bjw321** [Eternaldeath/blockchainHome#5]
https://www.aliyundrive.com/s/zvdBghf8CMj

**Comment by Eternaldeath** [comment]
不好意思，才看到，感谢分享，将在下一次更新中提交，并标注分享者。

**Comment by Eternaldeath** [comment]
相关资源已经更新，并标注您为分享者，该 Issue 将被关闭。
