### ISSUE TITLE
第五届CCF中国区块链技术大会

### ISSUE THREAD

**Issue by CNZedChou** [Eternaldeath/blockchainHome#6]
> 因疫情延期的2022年第五届CCF中国区块链技术大会将于2023年2月10-12日在无锡举办。
会上发布《CCF区块链专委会区块链高水平学术期刊和学术会议目录》《CCF区块链学术研究白皮书》和《无锡市政务区块链创新应用指南》。
---
但是好像在网上没有找到相关的文件

**Comment by Eternaldeath** [comment]
收到，我会排查一下是否有相关已公开的资源，若存在资源，会在下一期更新中提供，并标记您为资源 proposal 者。

**Comment by Eternaldeath** [comment]
在网络上搜索了一下，也咨询了相关的朋友，目前没有公开的资料，以后有相关资料了再补充。

该 Issue 将被关闭。
